# Generated by Django 4.2.5 on 2023-09-14 15:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("categories", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=None, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "toprated",
                    models.BooleanField(default=False, help_text="1=toprated"),
                ),
                (
                    "bestseller",
                    models.BooleanField(default=False, help_text="1=bestseller"),
                ),
                ("title", models.CharField(max_length=200, verbose_name="title")),
                ("slug", models.SlugField(max_length=200, verbose_name="slug")),
                (
                    "description",
                    models.CharField(blank=True, verbose_name="description"),
                ),
                (
                    "price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        verbose_name="price ($)",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("publish", models.DateTimeField(default=django.utils.timezone.now)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("DF", "Draft"), ("PB", "Published")],
                        default="DF",
                        max_length=2,
                    ),
                ),
                (
                    "categories",
                    models.ManyToManyField(
                        related_name="category_products",
                        to="categories.category",
                        verbose_name="Categories",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product",
                "verbose_name_plural": "Products",
                "ordering": ["-publish"],
                "indexes": [
                    models.Index(
                        fields=["-publish"], name="products_pr_publish_ffbfbe_idx"
                    )
                ],
            },
        ),
    ]
